# Generated by Django 2.2.7 on 2020-03-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(blank=True, max_length=128, null=True)),
                ('menus', models.ManyToManyField(related_name='recipes', to='menus.Menus')),
            ],
            options={
                'db_table': 'recipe',
            },
        ),
    ]
