# Generated by Django 2.2.7 on 2020-03-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='menus',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='menus.Menus'),
        ),
    ]
