# Generated by Django 2.2.7 on 2020-03-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(blank=True, max_length=128, null=True)),
                ('recipes', models.ManyToManyField(related_name='ingredients', to='recipe.Recipe')),
            ],
            options={
                'db_table': 'ingredient',
            },
        ),
    ]
